// Alphabetized list of header fonts (URL-encoded for Google Fonts)
const HEADER_FONTS = [
  'Amatic+SC',
  'Autour+One',
  'Bad+Script',
  'Bubblegum+Sans',
  'Caveat',
  'Comfortaa',
  'Cormorant+Garamond',
  'Fugaz+One',
  'Gasoek+One',
  'Google+Sans+Flex',
  'Germania+One',
  'Gowun+Dodum',
  'Happy+Monkey',
  'Homemade+Apple',
  'Iceberg',
  'Josefin+Slab',
  'Kurale',
  'League+Script',
  'Lobster+Two',
  'Marvel',
  'Manufacturing+Consent',
  'Over+the+Rainbow',
  'Orbitron',
  'Pacifico',
  'Permanent+Marker',
  'Petemoss',
  'Playpen+Sans',
  'Playwrite+Argentina+Guides',
  'Protest+Guerrilla',
  'Protest+Revolution',
  'Raleway',
  'Rock+Salt',
  'Roboto+Mono',
  'Roboto+Slab',
  'Sancreek',
  'Sedgwick+Ave+Display',
  'Slackey',
  'Smooch+Sans',
  'Square+Peg',
  'Ultra',
  'VT323',
  'Walter+Turncoat'
]

export default HEADER_FONTS
